
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - redis_data:/data

  celery:
    build: ./backend
    container_name: celery
    command: celery -A backend worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - backend

  celery-beat:
    build: ./backend
    container_name: celery-beat
    command: celery -A backend beat -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: internal-ai-report-master
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
  redis_data:

