services:
  backend:
    networks:
      - mynet

  frontend:
    networks:
      - mynet

  db:
    networks:
      - mynet
  celery:
    networks:
      - mynet

  redis:
    networks:
      - mynet

  celery-beat:
    networks:
      - mynet

networks:
  mynet:
    external: true
