# Generated by Django 6.0.2 on 2026-03-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_embedding_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='content',
            field=models.JSONField(),
        ),
    ]
