# Generated by Django 6.0.2 on 2026-08-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_alter_report_conversation_savedreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sql_query',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='sql_query',
            field=models.TextField(),
        ),
    ]
